### ISSUE TITLE
高手你好 同行菜鸟dev

### ISSUE THREAD

**Issue by wolfwell5** [gavfu/chzhshch-blog-site#7]
我也炒股10年，也是搞IT的，求问你的项目本地如何启动呢？ 看着代码都是html啊，但是本地clone下来，chrome打开总会跳转到error 页面。

![image](https://github.com/gavfu/chzhshch-blog-site/assets/30484860/b5b885dd-d1ae-42d2-9f7c-3f24490831c0)

**Comment by gavfu** [comment]
$ npm install -g live-server
$ npx live-server

**Comment by wolfwell5** [comment]
感谢，可以本地运行了。 为此还专门学了下Docusaurus框架，楼主🐂的👍🏻

**Comment by wolfwell5** [comment]
有机会可以一起开发，或者一起炒股哈哈😄
